name: Terraform Apply (dev on main)

on:
  push:
    branches: [main]
    paths:
      - 'environments/dev/**'
      - '.github/workflows/apply-dev.yml'
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform-apply-dev
  cancel-in-progress: false

jobs:
  apply-dev:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: environments/dev
    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.x

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_DEV }}
          aws-region: ap-northeast-1

      - name: Terraform init
        run: terraform init -input=false -no-color

      - name: Terraform plan (for visibility)
        run: terraform plan -no-color -out=plan.out | tee plan_stdout.txt

      - name: Terraform apply (dev)
        run: terraform apply -auto-approve -input=false plan.out
