name: lint (infra)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run yamllint
        run: yamllint .
      - name: Run markdownlint
        run: npx --yes markdownlint-cli2 **/*.md
      - name: Validate JSON
        run: |
          set -e
          find . -type f -name "*.json" -print0 | xargs -0 -I{} sh -c 'jq . "{}" >/dev/null' || true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform fmt / validate (recursive, skip if no .tf)
        shell: bash
        run: |
          set -euo pipefail
          if git ls-files '*.tf' | grep -q .; then
            terraform fmt -check -recursive
            for d in $(git ls-files '*.tf' | xargs -n1 dirname | sort -u); do
              echo "==> terraform validate in $d"
              (cd "$d" && terraform init -backend=false -input=false -no-color && terraform validate -no-color)
            done
          else
            echo "No .tf files. Skip terraform checks."
          fi

      - name: Helm lint (if charts/ exists)
        shell: bash
        run: |
          if [ -d charts ]; then
            helm lint charts/* || true
          else
            echo "No charts/ directory. Skip helm lint."
          fi
